### ISSUE TITLE
Typo in 3.3 QuickStart Tutorial 

### ISSUE THREAD

**Issue by pbcGIS** [laminas/laminas-mvc#105]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.x.x

#### Summary
In   [laminas-mvc quick-start](https://github.com/laminas/laminas-mvc/blob/3.3.x/docs/book/quick-start.md)
the command for installing the skeleton application has a typo.

> $ composer create-project -sdev laminas/laminas-mvc-skeleton my-application

Should be 

> $ composer create-project -s dev laminas/laminas-mvc-skeleton my-application

Note the correct invocation of "-s dev"

**Comment by Ocramius** [comment]
Could you edit the file to send a patch directly from here, please?

**Comment by pbcGIS** [comment]
This is my very first time initiating a patch on gitHub.  Does "edit the file and send a patch" the same as "generate a pull request?"

Thanks for your patience.  I'm excited to learn how to contribute.

**Comment by Ocramius** [comment]
Yup, that would work :) 

Make sure you edit on the `3.3.x` branch, so your change can be published as a patch :+1: 

Also consider using a branch and commit message that makes sense (github UI should give you input fields for that)

**Comment by froschdesign** [comment]
Fixed with #107 and released with [version 3.3.3](https://github.com/laminas/laminas-mvc/releases/tag/3.3.3).
