### ISSUE TITLE
improvement: Adding examples for AbstractRestfulController actions

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#11]
Provide a narrative description of what you are trying to accomplish:

- [ ] Are you fixing a bug?
  - [ ] Detail how the bug is invoked currently.
  - [ ] Detail the original, incorrect behavior.
  - [ ] Detail the new, expected behavior.
  - [ ] Base your feature on the `master` branch, and submit against that branch.
  - [ ] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [x] Is this related to documentation?
  
  

---

Originally posted by @alessandrofeitoza at https://github.com/zendframework/zend-mvc/pull/286

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
