### ISSUE TITLE
Plea for Ukraine

### ISSUE THREAD

**Issue by afilina** [laminas/laminas-mvc#111]
As per the request of the technical steering committee, here is my draft of the message that we want to propagate. Once the draft's direction is approved, I'll open a PR for the nitty-gritty details. Finally, we will translate this to Russian.

---

Members of the Laminas team come from all over the world. Many of us have friends and family in both Russia and Ukraine. Some of us were born in Russia. Some of us currently live in Russia. Some have grandparents who fought Nazis in World War II. Nobody here supports fascism.

One team member has a Ukrainian relative who fled her home with her son. The train was delayed due to bombing on the road ahead. We have friends who are hiding in bomb shelters. We anxiously follow up on them after the air raids, which indiscriminately target hospitals, schools, kindergartens and houses. We're not taking this from any media. These are our actual experiences.

You trust us enough to use our software. We ask that you trust us to say the truth on this. We need your help. Go out and protest this unnecessary war. Stop the bloodshed. Say "no to war".

**Comment by afilina** [comment]
The approach I took:
- Not accusing or judging the Russian people.
- Not asking people to take a side, only stop the war.
- Share real stories, because we're real people.
- No mention of any event from the media. We don't want to debate fake news objections.
- Make it clear that we actually have Russians here, so it's not a patriotism issue.
- Remind where we stand on the question in fascism.
- As per the suggestion of the team, avoid a generic message.

**Comment by weierophinney** [comment]
This is beautiful, @afilina 

:+1: from me. Anybody else have comments?

**Comment by internalsystemerror** [comment]
Just that the right person was clearly asked to write this. Succinct and to the point and hopefully enough to elicit an inquisitive response.

**Comment by Ocramius** [comment]
I am a bit weirded out by the missing accusation, but if you believe that this will have a better impact on the readers in Russia, this can go in, IMO 👍

Thanks for the quick and powerful writeup, @afilina!

**Comment by weierophinney** [comment]
@afilina We have consensus here and in the #tsc-meeting channel. Can you provide a Russion translation of this for us as well, please? We'll then take that and start adding to the README.md of all our repos.

Thank you; you're amazing, and this is tremendously heartfelt and moving.

**Comment by afilina** [comment]
Currently translating.

**Comment by Xerkus** [comment]
This was applied across Laminas
