### ISSUE TITLE
AbstractRestfulController::patch returns array, not mixed

### ISSUE THREAD

**Issue by gregtyler** [laminas/laminas-mvc#114]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.3.3

#### Summary

`AbstractRestfulController::patch` has a typehint of `@return array` rather than `@return mixed` (which the other actions have).

#### Current behavior

This issue is highlighted by static analysis tools like PHPStan when you extend the class. If you try to set a return type of e.g. `JsonModel` or `ResponseInterface`, PHPStan (rightly) complains that the return type isn't compatible.

#### How to reproduce

N/A, it's just documentation

#### Expected behavior

I think it should return `mixed`, like the other methods. I'm happy to create a PR for this, but wanted to check I hadn't missed something first.

**Comment by Ocramius** [comment]
Changing the return type to `mixed` may break BC here, as it would mean that callers can expect anything, whereas they previously would expect `array` :thinking:

**Comment by Xerkus** [comment]
Following intended use of the return values in `AbstractController` and its descendants, `array` was never a valid return type as it is expected that `ViewModel` would be returned, with array just a convenience shortcut for `ViewModel`, while Response object as a return value would short circuit controller's `dispatch` event and would prevent `render` event entirely.

With that in mind, this is not a BC break.

**Comment by gregtyler** [comment]
Thanks both, with that in mind I've created #115 :)
