### ISSUE TITLE
Minor comment update

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#12]
The statement in `injectEventManager`'s comments that a shared event manager is injected into an existing event manager is incorrect - the code replaces the existing event manager with a new one.  That's what I updated.

I may have added too much 'how it works' detail, but I puzzled over this a bit so I thought the explanation might help future readers.

---

Originally posted by @bitwombat at https://github.com/zendframework/zend-mvc/pull/285

**Comment by weierophinney** [comment]
Also, I wonder about the pre-existing comment that "the conditional will always pass". I think that's true. Then does it need to be a conditional?


---

Originally posted by @bitwombat at https://github.com/zendframework/zend-mvc/pull/285#issuecomment-397136114

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
