### ISSUE TITLE
VS-Code error AbstractController in line 150: Cannot use ::class with dynamic class name

### ISSUE THREAD

**Issue by Bro3x** [laminas/laminas-mvc#154]
VS-Code gives me an error in Laminas\Mvc\Controller\AbstractController in line 150:

$className = $this::class;
"Cannot use ::class with dynamic class name"

Is there anything that I should be concerned about?

**Comment by Xerkus** [comment]
It is PHP 8.0 feature
> As of PHP 8.0.0, the ::class constant may also be used on objects. This resolution happens at runtime, not compile time. Its effect is the same as calling [get_class()](https://www.php.net/manual/en/function.get-class.php) on the object.
