### ISSUE TITLE
laminas-json is abandoned

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-mvc#177]
laminas-json is abandoned and should be removed from the implementation in AbstractRestfulController and from the 'require-dev' section in composer.json.
Reason: json_decode is available in all supported PHP versions.

Warning when running composer:
`Package laminas/laminas-json is abandoned, you should avoid using it. No replacement was suggested.`

composer.json
```
    "require-dev": {
        "laminas/laminas-coding-standard": "^2.5.0",
        "laminas/laminas-json": "^3.6",
        "phpunit/phpunit": "^10.5.38",
        "webmozart/assert": "^1.11"
    },
```

**Comment by froschdesign** [comment]
@matbech 
Help is welcome at any time! 😃 👍🏻

https://github.com/laminas/laminas-mvc/blob/5c5087e835e091b8d0510a26514b818b2ab96a8f/src/Controller/AbstractRestfulController.php#L623-L637
