### ISSUE TITLE
fixed SimpleStreamResponseSender ignored defined content length

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#2]
Provide a narrative description of what you are trying to accomplish:

We are using the stream HTTP response to directly stream file content from S3 to clients.
As we are dealing with video files we are using the the `Range`/`Content-Range` headers to allow clients to download specific parts of files.

To be able to do so we use the `Zend\Http\Response\Stream::setContentLength` method together with `fseek` to define the parts of the file to send.

Where `Stream::readStream` is dealing with the content length it's not handled in `SimpleStreamResponseSender` and the stream gets send until EOF.

To fix that this PR uses `stream_copy_to_stream` to `php://output` instead of `fpassthru` if a content length has been defined.

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

- [ ] Are you creating a new feature?
  - [ ] Why is the new feature needed? What purpose does it serve?
  - [ ] How will users use the new feature?
  - [ ] Base your feature on the `develop` branch, and submit against that branch.
  - [ ] Add only one feature per pull request; split multiple features over multiple pull requests
  - [ ] Add tests for the new feature.
  - [ ] Add documentation for the new feature.
  - [ ] Add a `CHANGELOG.md` entry for the new feature.

- [ ] Is this related to quality assurance?
  

- [ ] Is this related to documentation?
  
  

---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-mvc/pull/315

**Comment by alexmerlin** [comment]
Closing PR due to being inactive for more than 1 year.
