### ISSUE TITLE
Malformed request causes uncaught exception instead of 400 Bad Request

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#20]
https://github.com/zendframework/zend-http/issues/116 revealed that malformed HTTP request, in this case with header with empty value, leads to http request factory throwing exception.
Since it is happening early on during application bootstrap, it leads in turn to uncaught exception fatal error instead of proper `400 Bad Request` response. 

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-mvc/issues/226

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
