### ISSUE TITLE
Fatal error no catch in views

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#22]
When I have an exception in a "view" from a ViewHelper I recive a generic message :
"An error occurred during execution; please try again later.
No Exception available" without give me more info about the error.

But when I try same error in "layout" I recive this message "Fatal error: Uncaught Error:"  with additional information about the error (trace-files).

How you know, when not have information about error take a lot of time to debug.

Thanks for help

Environment: zf3 + php7 + ZendServer (Migration process of zf2  to zf3)

---

Originally posted by @wilariz at https://github.com/zendframework/zend-mvc/issues/199

**Comment by weierophinney** [comment]
I experienced same issue with view helper; we need more verbose error in view helper. I issued about it long time ago


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mvc/issues/199#issuecomment-246572349

**Comment by weierophinney** [comment]
related tweet by @akrabat : 

![need more verbose](https://cloud.githubusercontent.com/assets/459648/4800305/862175d4-5e24-11e4-84ac-324a393ca610.png)


---

Originally posted by @samsonasik at https://github.com/zendframework/zend-mvc/issues/199#issuecomment-246606415

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
