### ISSUE TITLE
Fix controller namespace in event manager

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#29]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7457
User: @0xPaul
Created On: 2015-04-22T09:29:40Z
Updated At: 2015-05-04T14:59:12Z
Body
Controller was only registering the root namespace, e.g. `Foo` instead of `Foo\Bar` for a class named `Foo\Bar\Baz`.

---
### Comment

User: @Martin-P
Created On: 2015-04-28T19:52:56Z
Updated At: 2015-04-28T19:52:56Z
Body
Perhaps you can add:
- a unittest which shows the correct namespace is returned
- a separate unittest which shows the wrong namespace is **not** returned

That way regressions can be avoided.

---
### Comment

User: @0xPaul
Created On: 2015-04-29T08:48:33Z
Updated At: 2015-04-29T08:48:33Z
Body
If by _you_, you mean _someone_, then yes. I'm sure _someone_ can do those things.

---
### Comment

User: @Martin-P
Created On: 2015-04-29T09:09:15Z
Updated At: 2015-04-29T09:09:15Z
Body

> If by _you_, you mean _someone_, then yes. I'm sure _someone_ can do those things.

I'm sure _someone_ can create unittests, but this is not _someone_s PR, it is your PR. So I meant you, @0xPaul  :wink:

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-mvc/issues/171

**Comment by weierophinney** [comment]
I have a Ns\SubNs\Controller\IndexController and confirm it is being picked up as Ns\SubNs... There is an undocumented feature, ```"view_manager" => ["controller_map" => ["Ns" => true]]``` which was required for the view templates to be in ns/subns/index as opposed to ns/index...

---

Originally posted by @internalsystemerror at https://github.com/zendframework/zend-mvc/issues/171#issuecomment-269695689

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
