### ISSUE TITLE
Flash Messenger Namespace Messages Return Nothing

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#30]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

---

Original Issue: https://api.github.com/repos/zendframework/zendframework/issues/7632
User: @tomshaw
Created On: 2015-09-29T20:01:05Z
Updated At: 2015-11-06T22:24:52Z
Body
Login controller:

<pre>
$this->flashMessenger()->addSuccessMessage('You have successfully logged in.');
</pre>

Forwarded Index Controller.

<pre>
no messages
$this->flashMessenger()->getSuccessMessages();
</pre>

Below works without vital namespace information.

<pre>
$this->flashMessenger()->addMessage('You have successfully logged in.');
</pre>

Forwarded Index Controller.

<pre>
$this->flashMessenger()->getMessages();
</pre>

---
### Comment

User: @mwillbanks
Created On: 2015-10-01T19:09:16Z
Updated At: 2015-10-01T19:09:16Z
Body
Hello @tomshaw I wanted to make sure I am understanding, you're stating that when you forward the controller (not redirect) that the flash messages are unavailable when using something like the addSuccessMessage vs. the addMessage.  Is this a correct statement?  The general case works properly but the specific case is not?

---
### Comment

User: @tomshaw
Created On: 2015-10-01T19:14:56Z
Updated At: 2015-10-01T19:14:56Z
Body
Ignore forward. Redirect after a successful login. 

---
### Comment

User: @tomshaw
Created On: 2015-10-01T19:20:11Z
Updated At: 2015-10-01T19:20:11Z
Body
Using an ajax action I need not only the message but message type, error, success, info etc. 

---

---

Originally posted by @GeeH at https://github.com/zendframework/zend-mvc/issues/168

**Comment by tomshaw** [comment]
@weierophinney Wow this was ages ago. Can't wait to checkout Laminas! I have no idea about the status of this been utilizing Expressive, I see moved to mezzio/mezzio. Happy New Year Cheers. 👍

**Comment by samsonasik** [comment]
closing as it is unclear what the flow of "ajax action" meant. please re-create issue if problem persist with better steps to reproduce, failing test case will be better.
