### ISSUE TITLE
Ability to specify response code on controller plugin redirect

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#4]
- [X ] I was not able to find an [open](https://github.com/zendframework/zend-mvc/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-mvc/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X ] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

I have changed my routing setup on a production app, and I would like to provide search engines with the information that a new URL format is being used. For this I would like to use code 301 (Permanently Moved) instead of 302 (Found).

### Code to reproduce the issue

In a controller action: 
```php
return $this->redirect()->toUrl('https://github.com'); //, ['statusCode' => 301]);
```

### Expected results

I should be able to specify a statusCode of choosing

### Actual results

The browser receives a 302 response code always.

Thanks for all your support!

---

Originally posted by @jroedel at https://github.com/zendframework/zend-mvc/issues/313

**Comment by weierophinney** [comment]
There is an open todo in the class of the redirect plugin:

https://github.com/zendframework/zend-mvc/blob/9f092ff24945f208047d99dff81f67de8862b5f4/src/Controller/Plugin/Redirect.php#L16

In the meantime you can use this workaround in any controller action:

```php
public function indexAction()
{
    $response = $this->getResponse();
    $response->getHeaders()->addHeaderLine(
        'Location',
        'https://github.com'
    );
    $response->setStatusCode(301);
    
    return $response;
}
```

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-mvc/issues/313#issuecomment-511568960

**Comment by samsonasik** [comment]
I created PR https://github.com/laminas/laminas-mvc/pull/61 for it

**Comment by chaos0815** [comment]
Would it be a solution to pass the desired status code as an optional parameter to the `toUrl()` method and as an `$option = ['statusCode' => 301]` to the `toRoute()` method?

**Comment by Ocramius** [comment]
As mentioned on slack ( https://laminas.slack.com/archives/C4R13GTRD/p1670227522366209 )

```php
return $this
    ->redirect()
    ->toUrl('https://github.com')
    ->setStatusCode(301);
```
