### ISSUE TITLE
Unable to resolve service "MvcTranslator" to a factory

### ISSUE THREAD

**Issue by rbbrioso28** [laminas/laminas-mvc#44]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.1.1

#### Summary

``Laminas\Mvc\Service\TranslatorServiceFactory`` is not exist

#### Current behavior

Fatal error: Uncaught Laminas\ServiceManager\Exception\ServiceNotFoundException: Unable to resolve service "MvcTranslator" to a factory; are you certain you provided it during configuration?

**Comment by michalbundyra** [comment]
@rbbrioso28 Probably we would need more information to help, but it looks like configuration/dependency issues, not a bug in the library itself.

I'd suggest to check if you have installed https://github.com/laminas/laminas-mvc-i18n and module is enabled in your configuration.

**Comment by rbbrioso28** [comment]
I just added this to my config, then it works
```
'service_manager' => [
    'factories' => [
        'MvcTranslator' => \Laminas\I18n\Translator\TranslatorServiceFactory::class,
    ],
    'aliases' => [
        'translator' => 'MvcTranslator',
    ]
],
```

**Comment by rbbrioso28** [comment]
https://docs.laminas.dev/laminas-mvc/services/

- MvcTranslator, mapping to Laminas\Mvc\Service\TranslatorServiceFactory, and returning an instance of Laminas\Mvc\I18n\Translator, which extends Laminas\I18n\Translator\Translator and implements Laminas\Validator\Translator\TranslatorInterface, allowing the instance to be used anywhere a translator may be required in the framework.

**Comment by michalbundyra** [comment]
As I said, you should have enabled `Laminas\Mvc\I18n` module, then all should be fine:

https://github.com/laminas/laminas-mvc-i18n/blob/edeae41a45de697e0efb2e01ee677217e80517db/src/ConfigProvider.php#L34-L48

Good that it's solved now.

**Comment by rbbrioso28** [comment]
this ``Laminas\Mvc\Service\TranslatorServiceFactory`` should be created on laminas-mvc to permanently fix the issue. hopefully on the next release.. thanks

**Comment by rbbrioso28** [comment]
this Laminas\Mvc\I18n is not existing too in its Laminas\I18n

**Comment by michalbundyra** [comment]
@rbbrioso28 Please read carefully what I said - install laminas-mvc-i18n and enable this module:

```bash
$ composer require laminas/laminas-mvc-i18n
```

More about enabling modules in your application you can read in the documentation:
https://docs.laminas.dev/laminas-mvc/intro/#configuring-the-module-manager

I would suggest using:
```php
composer require --dev laminas/laminas-component-installer
```

so then module will be registered automatically on composer require action.

**Comment by rbbrioso28** [comment]
oops.. my bad.. didn't notice this laminas-mvc-i18n module. my eyes focuses only on the mvc and i18n  
thanks a lot!!!!
