### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by mimmi20** [laminas/laminas-mvc#47]
### Bug Report

In the MiddlewareListener the `setResponsePrototype` is called. This method was removed in the MiddlewarePipe.

```php
Error: Call to undefined method Laminas\Stratigility\MiddlewarePipe::setResponsePrototype() in vendor/laminas/laminas-mvc/src/MiddlewareListener.php:135
Stack trace:
#0 vendor/laminas/laminas-mvc/src/MiddlewareListener.php(68): Laminas\Mvc\MiddlewareListener->createPipeFromSpec(Object(Laminas\ServiceManager\ServiceManager), Object(Laminas\Diactoros\Response), Array)
#1 vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\MiddlewareListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#2 vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#3 vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#4 public/index.php(43): Laminas\Mvc\Application->run()
#5 {main}
```

|    Q        |   A
|------------ | ------
| laminas/laminas-mvc  | 3.1.1
| laminas/laminas-psr7bridge | 1.2.1
| laminas/laminas-stratigility | 3.2.1
| laminas/laminas-eventmanager | 3.2.1
| PHP | 7.2.26

#### Summary

An error is raised when using the Middleware inside MVC.

#### Expected behavior

No Error when using the Middleware Feature inside MVC.

**Comment by michalbundyra** [comment]
@mimmi20 Thanks for reporting. Laminas MVC does not work with stratigility v3, only v2.

We have started new library for that integration - [laminas-mvc-middleware](https://github.com/laminas/laminas-mvc-middleware) but it is not completed yet.

For the time being you can use stratigility v2.

**Comment by mimmi20** [comment]
Thanks
