### ISSUE TITLE
Wrong primary key value assignment

### ISSUE THREAD

**Issue by EntityTechnologies** [laminas/laminas-mvc#48]
### Bug Report
**namespace:** Laminas\Db\RowGateway
**class method:** save()

There is a possible bug in following lines:
if (($primaryKeyValue = $result->getGeneratedValue()) && count($this->primaryKeyColumn) == 1) {
      $this->primaryKeyData = [$this->primaryKeyColumn[0] => $primaryKeyValue];
 }

**Explanation:**
$primaryKeyValue = $result->getGeneratedValue() assignment is wrong since the primary key value 
 holder could be a totally different column.  PDO, for example, returns the first generated auto increment value, while the primary column value could come from data itself (it could happen that it was set before)

#### Summary

**My suggestion:** First of all is to fetch the primary key from data based on primary column definition ($this->primaryKeyColumn[0]) and if nothing was found then fetch from generated value.

$lastInsertedValue = $result->getGeneratedValue();
if ($lastInsertedValue && count($this->primaryKeyColumn) == 1) {
    $primaryKeyValue = $this->data[$this->primaryKeyColumn[0]]; 
    if (!$primaryKeyValue) $primaryKeyValue = $lastInsertedValue;
    $this->primaryKeyData = [$this->primaryKeyColumn[0] => $primaryKeyValue];
}

**Comment by samsonasik** [comment]
please report to https://github.com/laminas/laminas-db repository. thank you ;)

**Comment by EntityTechnologies** [comment]
Will do, thanks!
