### ISSUE TITLE
Allow services from container

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-mvc#7]
Allow retrieving services from container in `ModuleManagerFactory`

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-mvc/pull/310

**Comment by weierophinney** [comment]
@weierophinney can you re-run the failed test?
With this PR I will able to use the same configured container from a zend-expressive configuration in a zend-mvc application, disabling the `ServiceListener::addServiceManager()` calls (and some other changes). 

It could be nice if we can cherry-pick on master for the next release.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-mvc/pull/310#issuecomment-474596844

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
