### ISSUE TITLE
Outdated doc page "Using middleware within event listeners"?

### ISSUE THREAD

**Issue by tempfirstuser** [laminas/laminas-mvc#78]
From laminas chat:

This doc https://docs.laminas.dev/laminas-mvc/cookbook/middleware-in-listeners/

@boesing  "thats actually an outdated version of how to work with middlewares in mvc"

This issue was requested by user (@ thomas from laminas chat)

**Comment by rieschl** [comment]
thanks @tempfirstuser , I'll try to look into it over the weekend!

**Comment by Xerkus** [comment]
This cookbook is not relevant and should be dropped entirely since double-pass middleware are not a thing anymore.

With the PSR middleware flow it is impossible to have them attached as listeners anymore.
