### ISSUE TITLE
`ControllerManager` service alias change breaks `laminas-mvc-console`

### ISSUE THREAD

**Issue by rtek** [laminas/laminas-mvc#99]
## BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.1

#### Summary

`laminas-mvc-console` uses a delegator to inject the console object into the container.
```
'ControllerManager'         => [ Service\ControllerManagerDelegatorFactory::class ],
```

`ControllerManger` was converted from a service to a service alias in `3.3.1`, so the delegator does not get invoked (you cannot delegate an alias).

#### Previous behavior

Console was available via `$serviceManager->get('Console')`

#### Current behavior

Console not available by default

#### Workaround

Add the delegator to your local services config

```
'delegators' => [
    \Laminas\Mvc\Controller\ControllerManager::class => [  \Laminas\Mvc\Console\Service\ControllerManagerDelegatorFactory::class ]
]
```

**Comment by Ocramius** [comment]
Hmm, I totally thought delegators would work on aliases too 🤔

**Comment by boesing** [comment]
Nope. They sadly never worked on aliases.
https://docs.laminas.dev/laminas-servicemanager/delegators/#delegator-factories-and-service-aliases

The documentation about this was added a few months back as it was not totally clear.

Would prefer that the delegators would only apply to those services which are requested via `Container#get` but as that would be a BC break for aliases, we have to swallow that pill. Maybe something we might want to add to SM v4 but I am not 100% sure if that works out well for non-servicemanager usages in mezzio projects (given the fact that plenty of containers can be used and not sure how the delegator logic is implemented in each of these projects).

**Comment by Ocramius** [comment]
@rtek are you able to send a patch for this? In practice, it does what you mentioned there, but it also needs to raise the minimum supported `laminas/laminas-mvc` version inside `laminas-mvc-console`.

Alternatively, we revert the patch here, and make it so that `'ControllerManager'` is the service, while `ControllerManager::class` is the alias.

**Comment by Ocramius** [comment]
Indeed, perhaps a revert/swap of this could be a better solution :thinking: 

Thoughts?

**Comment by boesing** [comment]
We might need to investigate if there were documentation changes regarding this behavior.
But for a quick fix, we should just revert the change to the config while creating a follow-up to verify that documentation matches actual implementation.

**Comment by rieschl** [comment]
> We might need to investigate if there were documentation changes regarding this behavior. But for a quick fix, we should just revert the change to the config while creating a follow-up to verify that documentation matches actual implementation.

sorry, that was [my PR](https://github.com/laminas/laminas-mvc/pull/96) that caused this bug.
I'll come up with a fix or reversion.

**Comment by rtek** [comment]
Unfortunately the service name is part API so the "short named" services have to remain (otherwise it would be like renaming a class or a method) and since `laminas-mvc-console` is abandoned, it cant accommodate the BC break. 

@rieschl: an alias of `ControllerManager::class  => 'ControllerManager'` would maintain BC and allow the FQCN to resolve.

Regarding delegators on aliases - my opinion is that aliases should be discourage since they result in strings that are part of the API. They're generally harder to discover, and harder to refactor than `::class` or constant style service references. Its been a long time but I think the SM predates `::class` and even the general adoption of namespaces, so I suspect the need for aliases was rooted somewhere in there. I think they're useful in userland and for migration, so I wouldn't abandon them outright.

I've had success with a pattern where the service names reside as constants (using a mechanism of your choice). Having an element to attach documentation is useful (e.g. `@deprecated, @internal, @see etc`).

```php
namespace Foo\Lib;

class Service 
{
    /**
     * @see \Foo\Lib\FooManager
     */   
    public const FOO_MANAGER = FooManager::class;

    /**
     * Provides a LoggerInterface to FOO_MANAGER
     */
    public const FOO_LOGGER = 'Foo\Lib\FOO_LOGGER'; //wouldnt want to use LoggerInterface::class as the name

    /**
     * @internal
     */
    public const BAR = Bar::class;
}

class ConfigProvider
{
   public function __invoke()
   {
      return [
         'dependencies' => [
               'factories' => [ 
                   Service::FOO_MANAGER => ...,
                   Service::FOO_LOGGER => ..., 
                   Service::BAR => ...,
              ]
         ]
      ];
   }
}
```

```php
namespace Userland\App;

use Foo\Lib\Service as FooService;

class ConfigProvider
{
   public function __invoke()
   {
      return [
         'dependencies' => [
              'delegators' => [
                  FooService:FOO_MANAGER => [ ... ]
              ],
              'services' => [
                 FooService::FOO_LOGGER => new MyFooLogger()
             ]
         ],
       
      ];
   }
}
```

This is a discussion about the SM so I can take it over there to elaborate.

**Comment by Ocramius** [comment]
Reverted in #100
